name: Go Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Experiment
        run: |
          cd mutation-test

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Golang mutation testing
        uses: rescDev/go-mutesting-action
        with:
          targets: main.go cmd/
          disabled: structinit/remove
          blacklist-file: gomutest.blacklist
          output: verbose
